trigger: none

resources:
  pipelines:
    - pipeline: CI
      source: CI
      trigger: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: anupkd/my-python-app

stages:
- stage: Deploy
  jobs:
  - job: LocalDeploy
    steps:

    - script: |
        echo "Pull latest image"
        docker pull docker.io/$(imageName):latest

        echo "Stop existing container if running"
        docker stop my-app || true
        docker rm my-app || true

        echo "Run new container"
        docker run -d -p 5000:5000 --name my-app docker.io/$(imageName):latest

        echo "Deployment complete"
        
      displayName: Simulated Deployment