trigger: none   # no CI trigger

schedules:
  - cron: "0 22 * * *"
    displayName: Daily 22:00 Build
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildDocker
  displayName: Build Docker Image
  steps:

    - checkout: self

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: my-python-app
        Dockerfile: '**/Dockerfile'
        tags: |
          latest