trigger: none   # no CI trigger

schedules:
  - cron: "0 22 * * *"
    displayName: Daily 22:00 Build
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildDocker
  displayName: Build Docker Image
  steps:

    - checkout: self

    - task: Docker@2
      inputs:
        containerRegistry: 'DockerTest'
        repository: 'anupkd/my-python-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest